export const products = [
  {
    id: "jacka-001",
    brand: "Zara",
    name: "Svart skinnjacka",
    size: "M",
    condition: "Mycket bra",
    color: "Svart",
    material: "Skinn",
    description: "Klassisk svart skinnjacka från Zara i mycket fint skick. Jackan är endast använd ett fåtal gånger och har inga synliga skador eller slitningar.",
    price: 350,
    image: "imgs/jacka.webp",
    alt: "Svart skinnjacka",
  },
  {
    id: "klänning-001",
    brand: "Mango",
    name: "Blommig sommarklänning",
    size: "S",
    condition: "Mycket bra",
    color: "Flerfärgad",
    material: "Bomull",
    description: "Söt blommig sommarklänning från Mango i mycket fint skick. Klänningen är lätt och luftig, perfekt för varma sommardagar.",
    price: 180,
    image: "imgs/dress.jpeg",
    alt: "Blommig sommarklänning",
  },

  {
    id: "bag-001",
    brand: "Vintage",
    name: "Brun handväska",
    size: "One size",
    condition: "Mycket bra",
    color: "Brun",
    material: "Läder",
    description: "Elegant brun handväska i vintage-stil. Väskan är i mycket fint skick och har en klassisk design som passar till många olika outfits.",
    price: 250,
    image: "imgs/bag.gif",
    alt: "Brun handväska",
  },
];
